colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = "disable"
disableImageOptimization = false
disableTextInHeader = false
smartTOC = true
smartTOCHideUnfocusedChildren = "enable"
defaultFeaturedImage = "featured.svg"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = "enable"
showRecentItems = 6
showMoreLink = "enable"
showMoreLinkDest = "/posts/study"
cardView = "enable"
cardViewScreenWidth = false
layoutBackgroundBlur = "enable"

[article]
showDate = "show"
showViews = false
showLikes = false
showDateOnlyInArticle = true
showDateUpdated = true
showAuthor = true
showHero = "show"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = "show"
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = "show"
showReadingTime = true
showTableOfContents = "show"
showTaxonomies = "show"
showAuthorsBadges = "show"
showWordCount = false
showZenMode = "show"
heroStyle = "big"

[list]
showHero = "show"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
groupByYear = true
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = "show"
showHero = false
showBreadcrumbs = "hide"
showViews = false
showLikes = false
showTableOfContents = "show"

[term]
showHero = "show"
showBreadcrumbs = "show"
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardViewScreenWidth = false
heroStyle = "background"

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
